name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: ['8.3']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, gd, zip
        coverage: xdebug
    
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Run unit tests
      run: composer test
      env:
        KINOPOISK_TOKEN: ${{ vars.KINOPOISK_TEST_API_KEY }}
    
    - name: Run PHPStan static analysis
      run: composer phpstan
    
    - name: Run PHP CodeSniffer
      run: composer phpcs
    
    - name: Generate test coverage
      run: composer test-coverage
      env:
        KINOPOISK_TOKEN: ${{ vars.KINOPOISK_TEST_API_KEY }}
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/clover.xml
        fail_ci_if_error: true